Team1CodeForReview
Jooshua/e4CompareFramework-team2 pull request #29
Opened 2020-12-04 17:25 UTC by CedricKapalla

Texteditor Implementierung mit generellen editor-tools (open, save, copy/paste/cut, etc.) fertig implementiert, mehreren tabs, öffnung und schließung von tabs, und word-/linecount.

txt, java, und xml Dateien können per Doppelklick vom internen file-explorer aus geöffnet werden.

Hat noch einige kleinere bugs (wordcount funktioniert nicht direkt nach dem öffnen, erst wenn ein zweiter Tab geöffnet wurde; öffnen eines tabs setzt nicht direkt den cursor), sollte aber ansonsten funktionieren.

2020-12-07 11:46 UTC, KamilRosiak requested changes
Formatiert mal den Code mit Strg-Shift +O und guckt mal, ob man die View irgendwie Modularisieren kann. Ich finde, der Controller ist schon ganz schön groß. 

Sonst sieht das schon recht gut aus.

2020-12-07 11:46 UTC, KamilRosiak commented on de.tu_bs.cs.isf.e4cf.text_editor/src/de/tu_bs/cs/isf/e4cf/text_editor/TextEditorViewController.java
> +	private static final String TEXT_EDITOR_VIEW_FXML = "TextEditorView.fxml";
Formatierung

2020-12-07 11:46 UTC, KamilRosiak commented on de.tu_bs.cs.isf.e4cf.text_editor/src/de/tu_bs/cs/isf/e4cf/text_editor/TextEditorViewController.java
> +public class TextEditorViewController {
Java Doc

2020-12-07 11:46 UTC, KamilRosiak commented on de.tu_bs.cs.isf.e4cf.text_editor/src/de/tu_bs/cs/isf/e4cf/text_editor/view/TextEditor.java
> +
Java Doc

2020-12-07 11:46 UTC, KamilRosiak commented on de.tu_bs.cs.isf.e4cf.text_editor/src/de/tu_bs/cs/isf/e4cf/text_editor/FileUtils.java
> +
Java Doc

2020-12-07 11:46 UTC, KamilRosiak commented on de.tu_bs.cs.isf.e4cf.text_editor/src/de/tu_bs/cs/isf/e4cf/text_editor/FileUtils.java
> +	private ServiceContainer services;
Das funktioniert glaube ich nicht weil sich die Klasse nicht im Kontext befindet

2020-12-07 11:46 UTC, KamilRosiak commented on de.tu_bs.cs.isf.e4cf.text_editor/src/de/tu_bs/cs/isf/e4cf/text_editor/FileUtils.java
> +			}
strg + shit +f  also auto formatierung mal auf allem drücken

2020-12-07 11:46 UTC, KamilRosiak commented on de.tu_bs.cs.isf.e4cf.text_editor/src/de/tu_bs/cs/isf/e4cf/text_editor/FileUtils.java
> +	 * @return String[] of length 2 with (absolute) filePath at index 0 and
was ist index 1 ?

2020-12-07 11:46 UTC, KamilRosiak commented on de.tu_bs.cs.isf.e4cf.text_editor/src/de/tu_bs/cs/isf/e4cf/text_editor/highlighter/JavaHighlighting.java
> +
JavaDoc

2020-12-07 11:46 UTC, KamilRosiak commented on de.tu_bs.cs.isf.e4cf.text_editor/src/de/tu_bs/cs/isf/e4cf/text_editor/extensions/ProjectExplorerFileExtension.java
> +		return null;
error :P

2020-12-07 11:46 UTC, KamilRosiak commented on de.tu_bs.cs.isf.e4cf.text_editor/src/de/tu_bs/cs/isf/e4cf/text_editor/highlighter/XMLHighlighting.java
> +
JavaDoc

2020-12-07 11:46 UTC, KamilRosiak commented on de.tu_bs.cs.isf.e4cf.text_editor/src/de/tu_bs/cs/isf/e4cf/text_editor/view/EditorTab.java
> +	 * Creates a new CodeArea and adds text to it, if any is given.
public static methoden sind immer ein guter hinweis auf ich extrahiere es in eine factory / builder / util Klasse

2020-12-07 11:46 UTC, KamilRosiak commented on de.tu_bs.cs.isf.e4cf.text_editor/src/de/tu_bs/cs/isf/e4cf/text_editor/view/TextEditor.java
> + */
Die Klasse ist halt echt ziemlich groß. Ich denke, ihr solltet eure View in Mehren FXML Files mit jeweiligen Controllern oder so schreiben damit das alles etwas übersichtlicher wird, bzw. ich weiß nicht, ob das so geht aber ein Versuch ist es sicherlich wert.

2020-12-07 11:46 UTC, KamilRosiak commented on de.tu_bs.cs.isf.e4cf.text_editor/src/de/tu_bs/cs/isf/e4cf/text_editor/view/TextEditor.java
> +	 */
Das kann man definitive schöner machen mit FXML spart pro methode locker 5-6 Zeilen.
onAction="#methodenName" im XML und dann mit @FXML die Methode annotieren.

2020-12-07 11:46 UTC, KamilRosiak commented on de.tu_bs.cs.isf.e4cf.text_editor/src/de/tu_bs/cs/isf/e4cf/text_editor/view/TextEditor.java
> +	/**
Dann braucht man auch diese Methoden alle nicht mehr

2020-12-07 14:13 UTC, Jooshua commented
Hey team01, wir werden euren PR reviewen nachdem ihr die Changes von @KamilRosiak eingebaut habt :)

Eine Sache die ich euch allgemein ans Herz legen möchte:
Ihr könnt auf Github Commits (/PRs) einem Ticket zuordnen, indem ihr in der Commit-Message die Nummer des Tickets mit #Nummer (z.B. #29) referenziert. Gleichzeitig das könnt ihr das auch bei PRs auf andere Repos (wie bei diesem) über die URL (z.B. https://github.com/CedricKapalla/e4CFTeam1WS20-21/issues/6). 
Mehr unter: https://guides.github.com/features/issues/

Das macht das ganze nachvollziehbarer und einfacher zu reviewen ;)

2020-12-12 10:24 UTC, timbittner commented on de.tu_bs.cs.isf.e4cf.text_editor/src/de/tu_bs/cs/isf/e4cf/text_editor/FileUtils.java
> +	 * @return String[] of length 2 with (absolute) filePath at index 0 and
probably nur doc typo, file-content at index 1

2020-12-12 11:43 UTC, timbittner commented on de.tu_bs.cs.isf.e4cf.text_editor/src/de/tu_bs/cs/isf/e4cf/text_editor/FileUtils.java
> +	public String readFile(File file) {
Method throws NPE and is not declared throwing.
Also handles other exceptions, seems inconsistent

2020-12-12 11:43 UTC, timbittner commented on de.tu_bs.cs.isf.e4cf.text_editor/src/de/tu_bs/cs/isf/e4cf/text_editor/FileUtils.java
> +			return "";
From javadoc this method should always return some kind of path.
Is the else branch some kind of error handling?

2020-12-12 11:43 UTC, timbittner commented on de.tu_bs.cs.isf.e4cf.text_editor/src/de/tu_bs/cs/isf/e4cf/text_editor/highlighter/SyntaxHighlighter.java
> +    private void initHighlighting(String fileType, CodeArea codeArea) {
Just put these two calls into the constructor?

2020-12-12 11:43 UTC, timbittner commented on de.tu_bs.cs.isf.e4cf.text_editor/src/de/tu_bs/cs/isf/e4cf/text_editor/highlighter/SyntaxHighlighter.java
> +	        	return;
`break` instead of `return `for void function

2020-12-12 11:43 UTC, timbittner commented on de.tu_bs.cs.isf.e4cf.text_editor/src/de/tu_bs/cs/isf/e4cf/text_editor/highlighter/SyntaxHighlighter.java
> +//         executor = Executors.newSingleThreadExecutor();
Is there a reason for this commented out code?

2020-12-15 11:30 UTC, kyshidar commented on de.tu_bs.cs.isf.e4cf.text_editor/src/de/tu_bs/cs/isf/e4cf/text_editor/highlighter/SyntaxHighlighter.java
> +	public void canceHighlighting() {
cancelHighlighting() misses the "l"

2020-12-15 11:32 UTC, kyshidar commented on de.tu_bs.cs.isf.e4cf.text_editor/src/de/tu_bs/cs/isf/e4cf/text_editor/highlighter/SyntaxHighlighter.java
> +			protected StyleSpans<Collection<String>> call() throws Exception {
missing exception handling - could stop the task execution

2020-12-15 12:39 UTC, Jooshua approved these changes
No additional changes from my side :)

2020-12-15 12:52 UTC, valipu approved these changes
Only short feedback that you could look into. Changes are not mandatory for approval.

2020-12-15 12:52 UTC, valipu commented on de.tu_bs.cs.isf.e4cf.text_editor/src/de/tu_bs/cs/isf/e4cf/text_editor/FileUtils.java
> +				System.out.println(e.getMessage());
Maybe dispatch the error message to the messageprovider if necessary at all or remove the print statement.

2020-12-15 12:52 UTC, valipu commented on de.tu_bs.cs.isf.e4cf.text_editor/src/de/tu_bs/cs/isf/e4cf/text_editor/FileUtils.java
> +			}
Maybe you could use a StringBuilder to avoid unnecessary object allocation.

2020-12-28 20:40 UTC, merged