Added Inline renaming
Jooshua/e4CompareFramework-team2 pull request #30
Opened 2020-12-06 19:13 UTC by Jooshua

- Created event for renaming
- New rename handler that fires the event
- Added listener to event in viewcontroller
- Added fx inline rename functionality to custom tree cell
- Added recursive renaming

Task #24

2020-12-06 19:42 UTC, valipu reviewed
We need to address the NP Problem when checking for types of the files. NP Problem most likely due to implementation of isProject in combination with our way to build the tree.

2020-12-07 11:54 UTC, KamilRosiak requested changes
Wie beim letzten Review schon guckt das ihr mal den Formatter nutzt.

2020-12-07 11:54 UTC, KamilRosiak commented on de.tu_bs.cs.isf.e4cf.parts.project_explorer/src/de/tu_bs/cs/isf/e4cf/parts/project_explorer/CustomTreeCell.java
>  		setOnDragOver(new EventHandler<DragEvent>() {
??

2020-12-07 11:54 UTC, KamilRosiak commented on de.tu_bs.cs.isf.e4cf.parts.project_explorer/src/de/tu_bs/cs/isf/e4cf/parts/project_explorer/CustomTreeCell.java
> +
Comment

2020-12-07 11:54 UTC, KamilRosiak commented on de.tu_bs.cs.isf.e4cf.parts.project_explorer/src/de/tu_bs/cs/isf/e4cf/parts/project_explorer/CustomTreeCell.java
> +
Nutzt Lamdas e ->{

}

2020-12-07 11:54 UTC, KamilRosiak commented on de.tu_bs.cs.isf.e4cf.parts.project_explorer/src/de/tu_bs/cs/isf/e4cf/parts/project_explorer/CustomTreeCell.java
> +	public Node getImage(Object element) {
Auslagern in eine NodeFactory oder so

2020-12-07 11:54 UTC, KamilRosiak commented on de.tu_bs.cs.isf.e4cf.parts.project_explorer/src/de/tu_bs/cs/isf/e4cf/parts/project_explorer/controller/ProjectExplorerViewController.java
> +	/**
Subscribing on the Rename Event

2020-12-07 11:54 UTC, KamilRosiak commented on de.tu_bs.cs.isf.e4cf.parts.project_explorer/src/de/tu_bs/cs/isf/e4cf/parts/project_explorer/handlers/RenameHandler.java
>  public class RenameHandler {
Comment

2020-12-07 11:54 UTC, KamilRosiak commented on de.tu_bs.cs.isf.e4cf.parts.project_explorer/src/de/tu_bs/cs/isf/e4cf/parts/project_explorer/handlers/RenameHandler.java
> -
Was hier für eine Bombe Explodiert ^^

2020-12-07 16:39 UTC, valipu commented on de.tu_bs.cs.isf.e4cf.parts.project_explorer/src/de/tu_bs/cs/isf/e4cf/parts/project_explorer/CustomTreeCell.java
>  		setOnDragOver(new EventHandler<DragEvent>() {
konnte entfernt werden durch Implementierung einer Klasse für die Images der Files.

2020-12-08 10:18 UTC, kyshidar approved these changes

2020-12-13 14:50 UTC, merged